import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title> Example application for error happening when revalidating page</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <script type="application/javascript">
                </script>
            </Head>
            <main>
                <h1 id="example-application-for-error-happening-when-revalidating-page">Example application for error
                    happening
                    when revalidating page</h1>

                <ul style={{padding: "20px"}}>
                    <li ><a style={{marginTop: "5px"}}
                        href="/api/revalidate-server-page-normal-rendering">/api/revalidate-server-page-normal-rendering</a>
                    </li>
                    <li>
                        <a style={{paddingTop: "5px"}}
                            href="/api/revalidate-server-page-get-server-side-props-rendering">/api/revalidate-server-page-get-server-side-props-rendering</a>
                    </li>
                </ul>
            </main>
        </>
    )
}
